[package]
name = "lasv2"
version = "0.1.0"
edition = "2024"
license-file = "../LICENSE"
description = "Faithful port of LAPACK's LASV2 subroutine."

[dependencies]
num-traits = "0.2.19"

[dev-dependencies]
approx = "0.5.1"
faer = "0.22.6"
rstest = "0.26.1"
